### ISSUE TITLE
[Bug] SolidJS component size?

### ISSUE THREAD

**Issue by HummingMind** [motiondivision/motionone#116]
**1. Describe the bug**

Hello,
I have an Astro project set up (it uses Vite) with SolidJS integration and Motion One for Solid.
Things seems to work but the JavaScript output file size seems large.

Only importing Motion from "@motionone/solid" in my SolidJS component (Burger menu) makes the component size go up by 14 KB in addition to the shared chunk going up 7 KB (this one is to be expected) after build. Please see the screenshots:

**4. Expected behavior**

I would think the shared chunk would go up by about 6-7KB, but the component shouldn't increase in size too much.

**5. Video or screenshots**

Before:

![image](https://user-images.githubusercontent.com/87399963/180662713-add32433-6b57-4049-8ed2-a36bdc542165.png)

After:

![image](https://user-images.githubusercontent.com/87399963/180662755-553a9c02-35e5-4816-9cfa-ba0bfb51d9c0.png)

Is this normal?

Thank you.

**Comment by davedbase** [comment]
I lack knowledge regarding how bundlers work but here's my best guess.

The minified version of @motionone/solid is 16.1kb [according to Bundlephobia](https://bundlephobia.com/package/@motionone/solid@10.13.1). That includes Motion core + Solid binding. Your 14kb is likely just under the actual library size of 16.1kb (minified) because you're not using all the utilities ie. the Presence component gets tree shaken out and so the bundle is smaller.

You can see the breakdown of the dependency sizes [here](https://bundlephobia.com/package/@motionone/solid@10.13.1#result__section-heading). @motionone/dom is about 52% of that size.

In regards to why it bloats your component, it's because that particular chunk is shipping the dependencies which might be how Astro delivers the component. I believe there may be a way to ship the dependencies in different chunks but that goes beyond my knowledge.

Ultimately the gzip size (which is the real metric here) is 6kb. That's still a bit chunky for just what I assume is a hamburger asset. If you're using Motion elsewhere then I suspect the bundler will ship it differently? That's a question for Astro.

If you would like something smaller then perhaps using something like [solid-transition-group](https://github.com/solidjs/solid-transition-group) would work. This is really a trade-off between using a powerful library like Motion vs basic CSS.

**Comment by HummingMind** [comment]
@davedbase,
Thank you for the response! The main page for Motion One for Solid describes it as 5.8 KB in size. That threw me off, as it doesn't mention minification/compression.

I should have checked bundle phobia. It's showing there as 6.3 KB.

My total JS size went up 8.5 KB (compressed), which is more than both 5.8 KB and 6.3 KB.
It's by no means terrible. I just wasn't sure if I have something set up incorrectly.

I'll play around with multiple components to see how the bundler will handle it.

Thank you.

**Comment by HummingMind** [comment]
Creating another component that uses Motion One for Solid:

![image](https://user-images.githubusercontent.com/87399963/180665305-fda34999-ce9c-4151-9ea6-23cdce9862d6.png)

There is the 5.86 KB, as advertised :D

But the Wen chunk also went up. I wonder if that is the Astro JavaScript islands code that is going in there.

**Comment by HummingMind** [comment]
I ended up using the WAAPI inside my component directly for now.

Thank you anyway for taking the time to respond! :)

**Comment by davedbase** [comment]
Ah yeah, the Vue documentation does the same thing so when I ported the docs I just copied its structure. I suppose we could add in 5.8 [minified+gzip] for clarity but that's something @mattgperry should make a decision on.
