### ISSUE TITLE
[Feature] animate css variables itself

### ISSUE THREAD

**Issue by Taigistal** [motiondivision/motionone#119]
Is it possible to animate css variables itself?

In this nice Pokemon cards example: 
https://codepen.io/simeydotme/pen/abYWJdX
made with svelte motion, they are animating the css variables.

Is something like this possible?
And does it even make sense performance-wise?

```js
animate(
  ".wrapper",
  {
    "--t1": "400px"
  },
  {
    duration: 2,
    repeat: Infinity
  }
)
```
I know that svelte motion is based on framer motion/popmotion and think i understand the difference to the WAAPI-Approach from Motion One, but i wondered why it shouldn't be possible to change a css variables itself, isn't it a property like any other?

```js
const wrapper = document.getElementById("wrapper");
animate(
  progress => {
    wrapper.style.setProperty("--t1", `${progress * 400}px`)
  },
  {
    duration: 2,
    repeat: Infinity
  }
)
```

**Comment by mattgperry** [comment]
I think it is possible but only browswrs where CSS.registerProperty() exists - otherwise WAAPI doesn’t know how to animate these values

**Comment by Taigistal** [comment]
I tried it here: https://codepen.io/crioco/pen/abYEKRQ
But it doesn't seem to be working.

I use Chrome (Version 103.0.5060.134) on Mac OS and CSS.registerProperty() is available.

**Comment by mattgperry** [comment]
I should have been clearer you  have to actually call it https://developer.mozilla.org/en-US/docs/Web/API/CSS/RegisterProperty

**Comment by mattgperry** [comment]
Apologies I was on a phone and missed your initial example too.

For your second example you need to call `CSS.registerProperty`

But doing it like your first example works as expected: https://codepen.io/SirHound/pen/ZExvVGz

**Comment by mattgperry** [comment]
From your initial post, the second example in there is how Framer Motion is actually working under the hood.

We can't do that with Motion One as part of the benefit of using WAAPI is getting all the expensive interpolator code for free. Framer/Svelte Motion etc bundle all this in, and it isn't generally as good as what's included in the browser.

Which is why this currently only works with browsers that support `CSS.registerProperty`.

It's not too difficult to go from what we have now to allowing the animation of number CSS variables in all browsers as that's basically how the independent transform code is working. We could additionally support unit values for pretty cheap. But anything more complicated than that is difficult.

**Comment by Taigistal** [comment]
Thanks for the Explanation and your patience. Honestly, i'm not sure if I fully get it.

1. This one works even if `CSS.registerProperty` is not available.
```js
const wrapper = document.getElementById("wrapper");
animate(
  progress => {
    wrapper.style.setProperty("--t1", `${progress * 400}px`)
  },
  {
    duration: 2,
    repeat: Infinity
  }
)
```
and if i understand it right there is no WAAPi working in the background. 
So far I still understand it, I think

2. This one does not work in any browser, even if i call CSS.registerProperty
```js
window.CSS.registerProperty({
  name: '--t1',
  inherits: true,
  initialValue: '0',
});

animate(
  ".wrapper",
  {
    "--t1": "400px"
  },
  {
    duration: 2,
    repeat: Infinity
  }
)
````

I do understand that Motion One let the browser (WAAPI) do the complex unit calculation, but i dont understand why the browser can't calculate the change in my variable.

What is the differnece between animating to: `"--t1": "400px"`and `transform: "translateX(400px)`. Isn't that why I call "CSS.registerProperty" so that the browser understands the variable like any other CSS property?

Sorry for so many questions.

**Comment by mattgperry** [comment]
Your explanation for point 1 is good. Point 2 there must be something amiss with the code because this technique is how we animate independent transforms in Chrome. I think `syntax` is marked as optional in MDN but try adding `syntax: "<length>"` to the `registerProperty` call as that's the fundamental difference here (to answer your question), without this nothing has actually changed in terms of the browser's understanding of the value except you've added some rules around defaults and inheritence.

**Comment by Taigistal** [comment]
Wow, thanks.
I was about to give up, but it works.
